spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Microservicios
          jwk-set-uri: http://localhost:8080/realms/Microservicios/protocol/openid-connect/certs
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        serviceId: config-service
        enabled: true
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: checkout-service
          uri: http://localhost:8087
          predicates:
            - Path=/checkout
          filters:
            - AddRequestHeader=X-Request-from, Gateway
            - AddResponseHeader=X-Response-from, Checkout
        - id: Products-service
          uri: http://localhost:8081
          predicates:
            - Path=/productos
          filters:
            - AddRequestHeader=X-Request-from, Gateway
            - AddResponseHeader=X-Response-from, Prducts
eureka:
  instance:
    hostname: localhost

server:
  port: 8084
  
