spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        serviceId: config-service
        enabled: true
    gateway:
      routes:
        - id: checkout-service
          uri: http://localhost:8080
          predicates:
            - Path=/checkout
          filters:
            - AddRequestHeader=X-Request-from, Gateway
            - AddResponseHeader=X-Response-from, Checkout

eureka:
  instance:
    hostname: localhost

server:
  port: 8084
